version: '3'

services:
  bitcoin:
    image: zetachain/bitcoin:29-mainnet
    platform: linux/amd64
    environment:
      - bitcoin_username=test
      - bitcoin_password=test
      - NETWORK_HEIGHT_URL=https://blockstream.info/api/blocks/tip/height
      - WALLET_NAME=tssMainnet
      - WALLET_ADDRESS=bc1qm24wp577nk8aacckv8np465z3dvmu7ry45el6y
      - SNAPSHOT_URL=https://storage.googleapis.com/archive-rpc-snapshots-zetachain-dev/bitcoin.tar
      - SNAPSHOT_RESTORE=true
    volumes:
      - bitcoin_data:/root/.bitcoin/
    ports:
      - 8332:8332

volumes:
  bitcoin_data: