name: Node Operations - Athens2
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Which environment to update?'
        type: environment
        required: true
      ZETACORED_STATUS:
        description: 'Do you want to start, stop, or restart the zetacored?'
        type: choice
        options:
          - 'start'
          - 'stop'
          - 'restart'
        required: true
      ZETACLIENTD_STATUS:
        description: 'Do you want to start, stop, or restart the zetaclientd?'
        type: choice
        options:
          - 'start'
          - 'stop'
          - 'restart'
        required: true

env:
  AWS_REGION: "us-east-1"

jobs:
  start-stop-processes:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.ENVIRONMENT }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Pipeline Dependencies
        uses:  ./.github/actions/install-dependencies

      # - name: setup-git-credentials
      #   uses: de-vri-es/setup-git-credentials@v2.0.8
      #   with:
      #     credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }} 
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Change Zetacored Status
        run: |
          source .github/actions/deploy-binaries/functions
          COMMAND_ID=$(run_ssm_cmds_validators "systemctl ${{ github.event.inputs.ZETACORED_STATUS }} cosmovisor")
          check_cmd_status $COMMAND_ID
          COMMAND_ID=$(run_ssm_cmds_api_nodes "systemctl ${{ github.event.inputs.ZETACORED_STATUS }} cosmovisor")
          check_cmd_status $COMMAND_ID
          COMMAND_ID=$(run_ssm_cmds_archive_nodes "systemctl ${{ github.event.inputs.ZETACORED_STATUS }} cosmovisor")
          check_cmd_status $COMMAND_ID


      - name: Change Zetaclientd Status
        run: |
          source .github/actions/deploy-binaries/functions
          COMMAND_ID=$(run_ssm_cmds_validators "systemctl ${{ github.event.inputs.ZETACLIENTD_STATUS }} zetaclientd")
          check_cmd_status $COMMAND_ID

